"""create budget/budget_line/fx_rate (YYYYMM)

Revision ID: 2563d57f2a78
Revises: da89cf26bd3d
Create Date: 2025-11-15 21:10:05.955735

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2563d57f2a78"
down_revision: Union[str, None] = "da89cf26bd3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_table(
        "budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budget_user_id"), "budget", ["user_id"], unique=False)
    op.create_table(
        "fx_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rate_to_base", sa.Float(), nullable=False),
        sa.Column("valid_ym", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fx_rate_code"), "fx_rate", ["code"], unique=False)
    op.create_index(op.f("ix_fx_rate_user_id"), "fx_rate", ["user_id"], unique=False)
    op.create_index(op.f("ix_fx_rate_valid_ym"), "fx_rate", ["valid_ym"], unique=False)
    op.create_table(
        "budget_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("budget_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("income", "expense", name="linetype"), nullable=False
        ),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subcategory", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("monthly", "one_time", name="frequency"),
            nullable=False,
        ),
        sa.Column("start_ym", sa.Integer(), nullable=True),
        sa.Column("end_ym", sa.Integer(), nullable=True),
        sa.Column("one_time_ym", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budget.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_line_budget_id"), "budget_line", ["budget_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_line_end_ym"), "budget_line", ["end_ym"], unique=False
    )
    op.create_index(
        op.f("ix_budget_line_frequency"), "budget_line", ["frequency"], unique=False
    )
    op.create_index(
        op.f("ix_budget_line_one_time_ym"), "budget_line", ["one_time_ym"], unique=False
    )
    op.create_index(
        op.f("ix_budget_line_start_ym"), "budget_line", ["start_ym"], unique=False
    )
    op.create_index(op.f("ix_budget_line_type"), "budget_line", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_budget_line_type"), table_name="budget_line")
    op.drop_index(op.f("ix_budget_line_start_ym"), table_name="budget_line")
    op.drop_index(op.f("ix_budget_line_one_time_ym"), table_name="budget_line")
    op.drop_index(op.f("ix_budget_line_frequency"), table_name="budget_line")
    op.drop_index(op.f("ix_budget_line_end_ym"), table_name="budget_line")
    op.drop_index(op.f("ix_budget_line_budget_id"), table_name="budget_line")
    op.drop_table("budget_line")
    op.drop_index(op.f("ix_fx_rate_valid_ym"), table_name="fx_rate")
    op.drop_index(op.f("ix_fx_rate_user_id"), table_name="fx_rate")
    op.drop_index(op.f("ix_fx_rate_code"), table_name="fx_rate")
    op.drop_table("fx_rate")
    op.drop_index(op.f("ix_budget_user_id"), table_name="budget")
    op.drop_table("budget")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
