"""add transaction table

Revision ID: 6d1b7f4959f3
Revises: d9e3ca85e075
Create Date: 2025-11-20 23:30:13.271472

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # <-- keep this; avoids AutoString/NameError issues

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1b7f4959f3"
down_revision: Union[str, None] = "d9e3ca85e075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
