"""baseline all tables

Revision ID: b73d4b45a944
Revises: 6d1b7f4959f3
Create Date: 2025-11-22 12:46:19.394676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b73d4b45a944"
down_revision: Union[str, None] = "6d1b7f4959f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
