"""add transaction table

Revision ID: d9e3ca85e075
Revises: 2563d57f2a78
Create Date: 2025-11-20 23:21:37.812547

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9e3ca85e075"
down_revision: Union[str, None] = "2563d57f2a78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_fx_rate_code", table_name="fx_rate")
    op.drop_index("ix_fx_rate_user_id", table_name="fx_rate")
    op.drop_index("ix_fx_rate_valid_ym", table_name="fx_rate")
    op.drop_table("fx_rate")
    op.drop_index("ix_budget_line_budget_id", table_name="budget_line")
    op.drop_index("ix_budget_line_end_ym", table_name="budget_line")
    op.drop_index("ix_budget_line_frequency", table_name="budget_line")
    op.drop_index("ix_budget_line_one_time_ym", table_name="budget_line")
    op.drop_index("ix_budget_line_start_ym", table_name="budget_line")
    op.drop_index("ix_budget_line_type", table_name="budget_line")
    op.drop_table("budget_line")
    op.drop_index("ix_budget_user_id", table_name="budget")
    op.drop_table("budget")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_budget_user_id", "budget", ["user_id"], unique=False)
    op.create_table(
        "budget_line",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("budget_id", sa.INTEGER(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=7), nullable=False),
        sa.Column("category", sa.VARCHAR(), nullable=False),
        sa.Column("subcategory", sa.VARCHAR(), nullable=True),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.Column("currency", sa.VARCHAR(), nullable=False),
        sa.Column("frequency", sa.VARCHAR(length=8), nullable=False),
        sa.Column("start_ym", sa.INTEGER(), nullable=True),
        sa.Column("end_ym", sa.INTEGER(), nullable=True),
        sa.Column("one_time_ym", sa.INTEGER(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budget.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_budget_line_type", "budget_line", ["type"], unique=False)
    op.create_index(
        "ix_budget_line_start_ym", "budget_line", ["start_ym"], unique=False
    )
    op.create_index(
        "ix_budget_line_one_time_ym", "budget_line", ["one_time_ym"], unique=False
    )
    op.create_index(
        "ix_budget_line_frequency", "budget_line", ["frequency"], unique=False
    )
    op.create_index("ix_budget_line_end_ym", "budget_line", ["end_ym"], unique=False)
    op.create_index(
        "ix_budget_line_budget_id", "budget_line", ["budget_id"], unique=False
    )
    op.create_table(
        "fx_rate",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("code", sa.VARCHAR(), nullable=False),
        sa.Column("rate_to_base", sa.FLOAT(), nullable=False),
        sa.Column("valid_ym", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fx_rate_valid_ym", "fx_rate", ["valid_ym"], unique=False)
    op.create_index("ix_fx_rate_user_id", "fx_rate", ["user_id"], unique=False)
    op.create_index("ix_fx_rate_code", "fx_rate", ["code"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    # ### end Alembic commands ###
